# Find the CURL library

SET(_curl_SEARCH_DIRS
  /usr/local
  /usr/
)

FIND_LIBRARY(CURL_LIBRARY
  NAMES
    curl
  HINTS
    ${_curl_SEARCH_DIRS}
  PATH_SUFFIXES
    lib64 lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(curl REQUIRED_VARS CURL_LIBRARY)

IF(CURL_FOUND)
  SET(CURL_LIBRARIES ${CURL_LIBRARY})
ENDIF(CURL_FOUND)

MARK_AS_ADVANCED(
  CURL_LIBRARY
)
